class HomeController < ApplicationController
  def index
    @groups = [
      ["lunch","G029RFQA6"],
      ["perforce", "G029TL68S"],
      ["technical-discussion", "G029RL5PQ"],
      ["watercooler", "G029CMT1P"]]

    @users = ['ALEX ARSON', 'ALFONSE RAPISTKILLER', 'ANGELO BRASSKNUCKLE', 'ARNOLD TWATPOUNDER', 'AXE BURLY', 'BLADE SPINERIPPER', 'BLAKE STONE', 'BOARD RAZORFIST', 'BRANDON BEERBONG', 'BROCK STEAL', 'BRONT TRUNKTHUMPER', 'BUCK LANDSLIDE', 'BUFF SMASHINGTON', 'BUFF STRONGMAN', 'BULK MURDERFIELD', 'BUSTER HYMEN', 'BUTTZ IRONDUKES', 'BUZZ KILLINGTON', 'CHAINSAW GUTFUCK', 'CHET BARBARIAN', 'CHRISTOPHER CYANIDE', 'CLENCH WONDERSHANK', 'COMMANDER KILLZONE', 'DEX DENTSTEEL', 'EDDIE VISCERATOR', 'EDGARDO COOZEHOUND', 'FELIX HEADSHOT', 'FRAGGLE DIAMONDCRUNCH', 'FRANKIE FULLCLIP', 'GREGORY BONESAW', 'GUY GUTTER', 'HARLEY STEELTOE', 'HUNT FRIGHTENING', 'JAM HEADSTRIKE', 'JAMES GASCHAMBERS', 'JAXX HUNTER', 'JENS MCSMASHEDUP', 'JERK SLAPPINGTON', 'JOHN JAY GENOCIDE', 'JOHNNY BROADSWORD', 'KARL BOULDER', 'KEITH KILLJOY', 'KIDD JAMESON', 'LANCE ARMSTRONG', 'LARRY BLOWNDOME', 'LUNGE KILLINGTON', 'MAD ROCKRAGE', 'MARLEY MCFUCK', 'MARTY BONEPICK', 'MAX FIGHTMASTER', 'NUTTS BALLSTOMP', 'OSCAR NINEMILLI', 'PETE BLOODLETTER', 'PINCH UNDERTHRUST', 'RAGE NIGHTSTALK', 'RAGNOR SLAGPOUNDER', 'RANDALL GUTSNATCHER', 'RAPIER MCSTABGUTS', 'REVEREND JIM BIGNUTZ', 'ROB HAMMER', 'ROCK BONEBREAKER', 'ROD GUNMAN', 'ROGUE STEALTHY', 'SAM FREEBASE', 'SCHYLER HATEFUCK', 'SERGEANT SLAUGHTER', 'SEX MCBALLSDEEP', 'SHAKE DAGGERPUNCH', 'SHATTER GLASSJAW', 'SLAB IRONSTROKE', 'SLEDGE DEFTBLOW', 'SLEDGE TALLROUGH', 'SLURGE ROCKMEAT', 'SMACK PUNCHDEATH', 'SMACK ROCKWELL', 'SNAKE EYEJAB', 'SPIKE RAILKILL', 'STOMP WITMATIMBS', 'SWIFT THUNDERBONER', 'TINY CUNTPUNCH', 'TURD BURGLINGTON', 'WALTER FINGERBANG', 'WILLIAM SNITCHSTITCHER', 'XANDER SLICEFLESH']
  end

  def submit
    puts 'gets to here'
    username = params[:username]
    text = params[:message]
    channel = params[:group]

    chat_request = Slackbot::ApiRequest::Base.new("chat.postMessage", {username: username, text: text, channel: channel})
    chat_request.make_request
    render :json => {:success => true }
  end
end
